/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;

/**
 *
 * @author Eesha Javaid
 */
public class final_addcourse extends javax.swing.JFrame {

    /**
     * Creates new form final_addcourse
     */
    String name, course,section;
    int check;
    public final_addcourse(String name, String course, String section) {
      
        this.name=name;
        this.course = course;
        this.section = section;
        initComponents();
        Controller c = new Controller();
        
        check = c.AddSubject(name, course, section);
        System.out.println(check);
        if(check==0)
            textfield.setText("Registration close");
        else if(check==1)
            textfield.setText("No seats available. Click notify if you wish to recieve notifications about seats in future");
        else if(check ==2)
            textfield.setText("Course has been registered");
   
        else if(check ==3)
            textfield.setText("You are already registered in this Course");
             textfield.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        notify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textfield = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Add Course");

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        notify.setText("Notify");
        notify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notifyMouseClicked(evt);
            }
        });

        textfield.setColumns(20);
        textfield.setRows(5);
        jScrollPane1.setViewportView(textfield);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(85, 85, 85)
                                .addComponent(notify)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(notify))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse_Sec(name, course).setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1MouseClicked

    private void notifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notifyMouseClicked
        // TODO add your handling code here:
        Controller c = new Controller();
        if(check==0)
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"You cannot enable notifications when the registration period is inactive");
        else if(check ==1)
        {
            c.UpdateNotify(name);
             JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"You can check the seat status from Check Notifications");
             c.notification(course, section,name);
        }
        else
             JOptionPane.showMessageDialog(JOptionPane.getRootFrame(),"Your registration process is complete. This option is not available.");
    }//GEN-LAST:event_notifyMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton notify;
    private javax.swing.JTextArea textfield;
    // End of variables declaration//GEN-END:variables
}
